#!/usr/bin/env python3
"""Generate a demo PDF client report using AccountingEngine data."""

from datetime import date, datetime, timedelta
from decimal import Decimal
from typing import Optional, List, Any
import os

try:
    from reportlab.lib.pagesizes import A4  # type: ignore
    from reportlab.lib import colors  # type: ignore
    from reportlab.lib.styles import getSampleStyleSheet  # type: ignore
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle  # type: ignore
    from reportlab.lib.units import mm  # type: ignore
except Exception as e:  # pragma: no cover - environment may not have reportlab
    raise ImportError(
        "reportlab is required to generate PDFs. Install with: `python -m pip install reportlab`"
    ) from e

from accounting_engine import AccountingEngine

OUTPUT = "demo_client_report.pdf"

# Branding for a global insurance company (B2B & B2C friendly)
COMPANY_NAME = os.environ.get("PHINS_COMPANY_NAME", "PHINS Insurance")
COMPANY_ADDRESS = os.environ.get("PHINS_COMPANY_ADDRESS", "Global HQ: 1 Insurance Way, London")
COMPANY_CONTACT = os.environ.get("PHINS_COMPANY_CONTACT", "contact@phins.example.com")


def build_report(customer_id: str, period_start: date, period_end: date, output: str = OUTPUT, demo: bool = True) -> str:
    """Build a client PDF for `customer_id` covering `period_start`..`period_end`.

    If `demo` is True the function creates a few demo allocations to populate the
    statement. Otherwise it relies on existing allocations posted in the
    `AccountingEngine` instance.
    """
    acc = AccountingEngine("ACC_PDF_DEMO", "PHINS Demo")

    if demo:
        # Create sample allocations (3 months) and post them
        policy_id = "POL-DEM-001"
        monthly_premium = Decimal('100.00')
        risk_pct = Decimal('75')

        for m in range(1, 4):
            bill_id = f"BILL_{customer_id}_M{m}"
            alloc = acc.create_allocation(
                bill_id=bill_id,
                policy_id=policy_id,
                customer_id=customer_id,
                total_premium=monthly_premium,
                risk_percentage=risk_pct
            )
            acc.post_allocation(alloc.allocation_id, "Demo Script")

    # Generate statement for period
    stmt = acc.get_customer_statement(customer_id, period_start, period_end)

    # Build PDF
    doc = SimpleDocTemplate(output, pagesize=A4, rightMargin=20*mm, leftMargin=20*mm, topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    story: List[Any] = []

    # Title
    story.append(Paragraph(f"{COMPANY_NAME} - Client Report", styles['Title']))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"Customer ID: <b>{stmt.customer_id}</b>", styles['Normal']))
    story.append(Paragraph(f"Statement Date: {stmt.statement_date.isoformat()}", styles['Normal']))
    story.append(Paragraph(f"Period: {stmt.period_start.isoformat()} to {stmt.period_end.isoformat()}", styles['Normal']))
    story.append(Spacer(1, 12))

    # Allocations table
    if not stmt.allocations:
        story.append(Paragraph("No allocations found for the selected period.", styles['Normal']))
    else:
        data = [["Date", "Total Premium", "Risk", "Savings", "Investment Route"]]
        for a in stmt.allocations:
            data.append([
                a.allocation_date.isoformat(),
                f"${a.total_premium:.2f}",
                f"${a.risk_premium:.2f}",
                f"${a.savings_premium:.2f}",
                a.investment_route.value if hasattr(a, 'investment_route') else 'N/A'
            ])

        t = Table(data, hAlign='LEFT', colWidths=[70*mm, 30*mm, 30*mm, 30*mm, 40*mm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ]))

        story.append(t)
        story.append(Spacer(1, 12))

    # Summary
    story.append(Paragraph("<b>Period Summary</b>", styles['Heading2']))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"Total Premium Paid: <b>${stmt.total_premiums:.2f}</b>", styles['Normal']))
    story.append(Paragraph(f"Total Risk Coverage: <b>${stmt.total_risk_coverage:.2f}</b>", styles['Normal']))
    story.append(Paragraph(f"Total Customer Savings: <b>${stmt.total_customer_savings:.2f}</b>", styles['Normal']))
    story.append(Spacer(1, 12))

    # Footer notes (contact and legal)
    story.append(Paragraph(f"This is a demo PDF generated by {COMPANY_NAME}. Figures are illustrative.", styles['Italic']))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"{COMPANY_ADDRESS} | {COMPANY_CONTACT}", styles['Normal']))

    # Footer with page number
    def _draw_footer(canvas: Any, doc: Any) -> None:
        """Draw a simple footer on each page. Types use `Any` because ReportLab types
        are not available to static type checkers in this environment.
        """
        canvas.saveState()
        # A4 is a (width, height) tuple from reportlab — ignore the height value
        try:
            width, _ = A4
        except Exception:
            # Fallback to mm-based calculation
            width, _ = (210 * mm, 297 * mm)
        footer_text = f"{COMPANY_NAME} — Confidential — Page {getattr(doc, 'page', 1)}"
        canvas.setFont("Helvetica", 8)
        canvas.drawRightString(width - (20 * mm), 15 * mm, footer_text)
        canvas.restoreState()

    doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)  # type: ignore[arg-type]
    return output


def _parse_date(s: Optional[str], default: date) -> date:
    if not s:
        return default
    return date.fromisoformat(s)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description='Generate client PDF report')
    parser.add_argument('--customer', '-c', default='CUST_INT_001', help='Customer id')
    parser.add_argument('--start', '-s', help='Period start date (YYYY-MM-DD)')
    parser.add_argument('--end', '-e', help='Period end date (YYYY-MM-DD)')
    parser.add_argument('--output', '-o', default=OUTPUT, help='Output PDF file')
    parser.add_argument('--no-demo', action='store_true', help="Do not create demo allocations")
    args = parser.parse_args()

    # default period: last 90 days
    today = date.today()
    default_end = today
    default_start = today - timedelta(days=90)

    period_start = _parse_date(args.start, default_start)
    period_end = _parse_date(args.end, default_end)

    out = build_report(args.customer, period_start, period_end, output=args.output, demo=not args.no_demo)
    print(f"Generated: {out}")


if __name__ == '__main__':
    main()
